name: main
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Set up Ant
        uses: cedx/setup-ant@v1
        with:
          optional-tasks: true
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: lib
          key: java-${{runner.os}}-ivy-${{hashFiles('ivy.xml')}}
          restore-keys: java-${{runner.os}}-ivy-
      - name: Install dependencies
        run: ant install
      - name: Run tests
        env:
          FREEMOBILE_ACCOUNT: ${{secrets.FREEMOBILE_ACCOUNT}}
          FREEMOBILE_API_KEY: ${{secrets.FREEMOBILE_API_KEY}}
        run: ant -emacs test
